
# MySQL连接路径配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_mongo?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&allowMultiQueries=true&useSSL=false
    username: root
    password: 735900998
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 100
      maximum-pool-size: 100
      max-lifetime: 1800000
      idle-timeout: 600000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      data-source-properties:
          cachePrepStmts: true
          prepStmtCacheSize: 250
          prepStmtCacheSqlLimit: 2048


# Mongodb连接路径配置
  data:
    mongodb:
      uri: mongodb://localhost:27017/my_mongodb
      
  # 设置job设置成不可用（因为Spring Batch在加载的时候job默认都会执行）
  batch:
    job:
      enabled: true
  thymeleaf:
    cache: false
    prefix: classpath:/public/thymeleaf/
      
      
# Mybatis配置
mybatis:
  type-aliases-package: com.jfinteck.dmq.mapper*
  mapper-locations: classpath:/mapper/**.xml
 